0.9.10, *.something should be a valid label

diff --git a/server/debian/atomiadns-database.postinst b/server/debian/atomiadns-database.postinst
--- a/server/debian/atomiadns-database.postinst
+++ b/server/debian/atomiadns-database.postinst
@@ -67,6 +67,20 @@ recreate_procedure() {
 	fi
 }
 
+alter_check_constraint() {
+	table="$1"
+	constraint_name="$2"
+	constraint="$3"
+
+	query="ALTER TABLE $table DROP CONSTRAINT $constraint_name; ALTER TABLE $table ADD CONSTRAINT $constraint_name CHECK $constraint"
+
+	sudo -u postgres psql -c "$query" zonedata > /dev/null 2>&1
+	if [ $? != 0 ]; then
+		echo "error altering check constraint $table/$constraint_name, you'll have to migrate the schema manually."
+		exit 1
+	fi
+}
+
 set_schema_version() {
 	sudo -u postgres psql -c "UPDATE atomiadns_schemaversion SET version = $1" zonedata > /dev/null 2>&1
 	if [ $? != 0 ]; then
@@ -83,10 +97,10 @@ if [ $? != 0 ]; then
 		echo "database zonedata already exist, but doesn't contain the atomiadns schema. You will have to make sure that the schema matches /usr/share/atomiadns/schema manually"
 		exit 1
 	else
-		if [ "$schema_version" = 10 ]; then
+		if [ "$schema_version" = 11 ]; then
 			echo "The installed schema is the latest version, keeping the database as it is."
-		elif [ -n "$(echo "$schema_version" | grep -E '^[0-9]+$')" ] && [ "$schema_version" -lt 10 ]; then
-			echo "Schema version is $schema_version, and the latest database schema is version 10. Upgrading."
+		elif [ -n "$(echo "$schema_version" | grep -E '^[0-9]+$')" ] && [ "$schema_version" -lt 11 ]; then
+			echo "Schema version is $schema_version, and the latest database schema is version 11. Upgrading."
 			recreate_procedure "setupdatesdisabled"
 			recreate_procedure "deletezone"
 			recreate_procedure "adddnsrecords"
@@ -95,7 +109,9 @@ if [ $? != 0 ]; then
 			recreate_procedure "getlabels"
 			recreate_procedure "getzone"
 
-			set_schema_version 10
+			alter_check_constraint "label" "label_format" "(label ~* '^(([*][.])?([a-z0-9_][a-z0-9_-]*)([.][a-z0-9_][a-z0-9_-]*)*)|[@*]\$')" 
+
+			set_schema_version 11
 		else
 			echo "database zonedata already exist, but contains a bad schema version ($schema_version), this should never happen and indicates a bug."
 			exit 1
