Fix so that the webapp starts on 12.04
Change-Id: I6801a2d1b43cbf2d872bdf94bf2ad919d5fac214

diff --git a/webapp/debian/upstart b/webapp/debian/upstart
--- a/webapp/debian/upstart
+++ b/webapp/debian/upstart
@@ -8,6 +8,12 @@ respawn
 respawn limit 10 60
 
 script
+	node_bin=`whereis -b node | awk '{ print $2 }'`
+	if [ -z "$node_bin" ]; then
+		echo "can't find node binary"
+		exit 1
+	fi
+
 	if [ -f "/etc/atomiadns.conf" ]; then
 		init_env=`mktemp` || exit 1
 		temp_export=`mktemp` || exit 1
@@ -18,5 +24,5 @@ script
 		rm -f "$init_env" "$temp_export"
 	fi
 
-	exec /usr/local/bin/node /usr/lib/atomiadns/webapp/atomiadns.js >> /var/log/atomiadns_webapp.log 2>&1
+	exec "$node_bin" /usr/lib/atomiadns/webapp/atomiadns.js >> /var/log/atomiadns_webapp.log 2>&1
 end script
